FROM php:8.4-apache

# Habilita el módulo de reescritura de Apache
RUN a2enmod rewrite

# INSTALA LA EXTENSIÓN PDO PARA MYSQL (Línea obligatoria)
RUN docker-php-ext-install pdo pdo_mysql

# Copia todo el contenido al directorio del servidor
COPY . /var/www/html/

RUN chown -R www-data:www-data /var/www/html

ENV PORT=80
EXPOSE 80

CMD ["apache2-foreground"]
